# Generated by Django 5.0.4 on 2024-05-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelola_album_song', '0002_genre_songwriter_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='label',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Songwriter',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
